# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentComplex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('structure', models.CharField(blank=True, max_length=10, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_section', models.IntegerField()),
                ('building_phase', models.IntegerField()),
                ('floor', models.IntegerField()),
                ('on_floor_number', models.IntegerField()),
                ('space', models.DecimalField(decimal_places=2, max_digits=9)),
                ('price', models.IntegerField()),
                ('balcony', models.BooleanField()),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ApartmentComplex')),
            ],
        ),
    ]
